### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-ads-identifier

### ISSUE THREAD

**Issue by rymesaint** [OneSignal/OneSignal-Flutter-SDK#227]
**Description:**
I got this error yesterday, after some clean its work again. But today after i've clean using flutter clean still got this error.

```
Could not determine the dependencies of task ':app:compileSmkalwafaDebugJavaWithJavac'.
[        ] > Could not resolve all task dependencies for configuration ':app:smkalwafaDebugCompileClasspath'.
[        ]    > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
[        ]      Required by:
[        ]          project :app > com.onesignal:OneSignal:3.12.7
[        ]       > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
[        ]          > Unable to load Maven meta-data from
https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
[   +1 ms]             > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
[        ]                > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
[        ]                   > Read timed out
```

can you help me please?

**Environment**
OneSignal Flutter SDK 2.3.4

**Steps to Reproduce Issue:**

1. flutter run

**Comment by jkasten2** [comment]
@rymesaint JCenter does not host Google Libraries, make sure your `build.gradle` files have ` google()`  before `jcenter()`. Normally you just have to check `android/build.gradle`. It should look like this.
https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/2.3.4/android/build.gradle#L15-L20

**Comment by Sreejith93** [comment]
same error i have to

**Comment by Sreejith93** [comment]
What went wrong:
Could not determine the dependencies of task ':app:compileReleaseKotlin'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
     Required by:
         project :app > com.onesignal:OneSignal:3.12.7
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Could not list versions using M2 pattern 'https://jcenter.bintray.com/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/'.
                  > Read timed out

**Comment by FeifanChang** [comment]
I dont know why this problem happen sometimes.
and sometime it will be ok.

**Comment by daydreamer54** [comment]
I had the same error and when i did the following directory changes  then it's been solved and worked. (In this directory , Android - App - Build.gradle)

from this : 
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

to this one : 

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.google.gms.google-services'

**Comment by allumina** [comment]
I had a similar problem with gradle dependencies. @daydreamer54 solution works.

**Comment by rgomezp** [comment]
Howdy,
Glad to hear this is solved. Enjoy!

**Comment by Chris1234567899** [comment]
I'm afraid this is not solved. 
And for me the proposal of @daydreamer54 just results in another error:
```
A problem occurred evaluating project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.
```

Pls reopen this issue

**Comment by jkasten2** [comment]
@Chris1234567899 OneSignal does not require the `com.google.gms.google-services` Gradle plugin so you can safely omit it if you don't need it for anything else in your project.

If you do need it make sure you have correctly added it per Google's instructions
https://developers.google.com/android/guides/google-services-plugin

**Comment by Chris1234567899** [comment]
@jkasten2 
Thanks, no I do not need the gms plugin, I was just wondering where it came from (regarding the proposal of daydreamer).
Unfortunately the initial suggestion, putting google() before jcenter() did not solve it for me (I had it already in this order).
I copied the block from the onesignal docs as is to the app build.gradle. 
It was working until this morning, when suddenly the error appeared.

**Comment by daydreamer54** [comment]
@Chris1234567899
Actually I didn't add  " apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' " by heart. That time i was using Firebase Cloud Messaging so that i needed to add it and when i got this error i changed my code as i shared but if you don't need fcm then you should not add it again.
