### ISSUE TITLE
OneSignal Not Initializing [Bug]: 

### ISSUE THREAD

**Issue by jabirmayar** [OneSignal/OneSignal-Flutter-SDK#709]
### What happened?

i have in main function 
`  OneSignal.Debug.setLogLevel(OSLogLevel.fatal);

  OneSignal.initialize("appid");

  OneSignal.Notifications.requestPermission(true);`
  
 

### Steps to reproduce?

```Markdown
Add the latest version of package. 
Initialize onesignal
run app
```

### What did you expect to happen?

For appsignal to initialize and login user external id

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
`/MethodChannel#OneSignal( 3124): Failed to handle method call
E/MethodChannel#OneSignal( 3124): java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit
E/MethodChannel#OneSignal( 3124): 	at java.lang.reflect.Field.get(Native Method)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.start(TrackAmazonPurchase.kt:83)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.core.internal.startup.StartupService.start(StartupService.kt:16)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:247)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.flutter.OneSignalPlugin.initWithContext(OneSignalPlugin.java:128)
E/MethodChannel#OneSignal( 3124): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:111)
E/MethodChannel#OneSignal( 3124): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#OneSignal( 3124): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#OneSignal( 3124): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#OneSignal( 3124): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#OneSignal( 3124): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#OneSignal( 3124): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#OneSignal( 3124): 	at android.os.Looper.loop(Looper.java:268)
E/MethodChannel#OneSignal( 3124): 	at android.app.ActivityThread.main(ActivityThread.java:8019)
E/MethodChannel#OneSignal( 3124): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#OneSignal( 3124): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
E/MethodChannel#OneSignal( 3124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
I/System.out( 3124): [okhttp]:check permission begin!
I/System.out( 3124): [okhttp]:not MMS!
I/System.out( 3124): [okhttp]:not Email!
/flutter ( 3124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/flutter ( 3124): )
E/flutter ( 3124): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
E/flutter ( 3124): #1      MethodChannel._invokeMethod
platform_channel.dart:310
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124):
E/flutter ( 3124): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#lifecycleInit on channel OneSignal#inappmessages)
E/flutter ( 3124): #0      MethodChannel._invokeMethod
platform_channel.dart:308
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124): #1      OneSignalInAppMessages.lifecycleInit
inappmessages.dart:77
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124):
E/flutter ( 3124): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#pushSubscriptionToken on channel OneSignal#pushsubscription)
E/flutter ( 3124): #0      MethodChannel._invokeMethod
platform_channel.dart:308
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124): #1      OneSignalPushSubscription.lifecycleInit
pushsubscription.dart:65
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124):
E/flutter ( 3124): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#permission on channel OneSignal#notifications)
E/flutter ( 3124): #0      MethodChannel._invokeMethod
platform_channel.dart:308
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124): #1      OneSignalNotifications.lifecycleInit
notifications.dart:121
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124):
E/flutter ( 3124): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method OneSignal#requestPermission on channel OneSignal#notifications)
E/flutter ( 3124): #0      MethodChannel._invokeMethod
platform_channel.dart:308
E/flutter ( 3124): <asynchronous suspension>
E/flutter ( 3124): #1      OneSignalNotifications.requestPermission
notifications.dart:91
E/flutter ( 3124): <asynchronous suspension>`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SebastianoLaurent** [comment]
same issue

**Comment by KostyaLocal** [comment]
Same issue on MIUI on real device

**Comment by MobIS1User** [comment]
same issue for us

**Comment by Aboneyx** [comment]
same issue

**Comment by Chhay67** [comment]
same issue. any solution ????

**Comment by Aboneyx** [comment]
> same issue. any solution ????

rolled back to version 3.5.1

**Comment by ewingapp** [comment]
Same issue here, seems like no clear solution right now beside rolling back to previous version

**Comment by KostyaLocal** [comment]
> Same issue here, seems like no clear solution right now beside rolling back to previous version

I've rolled back too. Now I have problems with OneSignal.shared.setExternalUserId , OneSignal.shared.setEmail, OneSignal.shared.removeExternalUserId. They just take a long time to call

OneSignal is so buggy, are there any alternatives?

**Comment by metalwings** [comment]
Same issue here.
Version 5.0.0 works on iOS but causes android to crash.

Downgrading to 3.5.1 works for now.

**Comment by jabirmayar** [comment]
3.5.1 works, yes. but I would really like to use the latest as I already changed everything and i don't want to rollback. So I guess will have to wait for a fix.

**Comment by kryptamine** [comment]
same issue here

**Comment by khurramaleee** [comment]
Same issue crashing in release mode

**Comment by jblankenship5** [comment]
Updated all my code to new version just to have to rollback Zzz..

**Comment by emawby** [comment]
Thank you for reporting this is likely a "minify" issue with the Android native SDK. The fix should be available soon thank you for your patience!

**Comment by abudawud** [comment]
same issue when running the app on release mode `flutter run --release`.
but it's work fine on debug mode `flutter run`

**Comment by rafael-mq** [comment]
Check this answer on another issue: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/725#issuecomment-1710603403

**Comment by MaximilianFlechtner** [comment]
+1

**Comment by giovanni256** [comment]
> Check this answer on another issue: [#725 (comment)](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/725#issuecomment-1710603403)

Not working for this issue, +1

**Comment by emawby** [comment]
Thank you for reporting we are working on a fix for this asap!

**Comment by sharprockventures** [comment]
Thanks @emawby! I am having the same issue and just found this thread. Glad you guys are working on it!

**Comment by akanxa** [comment]
same issue any solution?

**Comment by talkbiz** [comment]
Same issue

**Comment by acvxx** [comment]
same issue

**Comment by KodyKendall** [comment]
Is there a short term workaround? I am running into this issue for the react-native SDK as well.

**Comment by akanxa** [comment]
same issue

**Comment by tuantung** [comment]
Same issue. iOS works fine. Only crashes with Android

**Comment by nan-li** [comment]
Hi everyone, 

Can you let me know if you are using any other in-app purchasing or purchases-related SDK in your app?

**Comment by akanxa** [comment]
Hi @nan-li, I used purchases_flutter, and it is working well after commenting this library.

**Comment by MobIS1User** [comment]
> Hi everyone,
> 
> Can you let me know if you are using any other in-app purchasing or purchases-related SDK in your app? And if you use Amazon IAP SDK?

We do not use any of those things in our Flutter app. Thanks for looking into it!

**Comment by nan-li** [comment]
Hi @akanxa, the OneSignal SDK works successfully if you remove `purchases_flutter`?

This is helpful information to help us resolve this bug.

**Comment by Klyado** [comment]
Same here with RevenueCat installed. It causes issues and breaks everything.  
I'm using Expo SDK but I guess that's the same problem.

**Comment by acvxx** [comment]
> Hi everyone,
> 
> Can you let me know if you are using any other in-app purchasing or purchases-related SDK in your app? And if you use Amazon IAP SDK?

I'm using both the "in_app_purchase" package and the "purchases_flutter" package. 
OneSignal SDK started working correctly after I removed the "purchases_flutter" package from RevenueCat.

**Comment by vegaro** [comment]
I work at purchases-flutter. I've been looking into this, and I believe the issue is in this line https://github.com/OneSignal/OneSignal-Android-SDK/blob/5.0.2/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/internal/purchases/impl/TrackAmazonPurchase.kt#L77. 

Method `e` changed in version 3.0.4 of the Amazon SDK (see https://www.diffchecker.com/mAggUTRG/ )

In 3.0.4

```
public boolean e() {
        this.h();
        return com.amazon.a.a.a((Application)this.e.getApplicationContext());
}
```

In 3.0.1, 3.0.2, 3.0.3

```
public static d e() {
        return c;
 }
```

`purchases-flutter` depends on version 3.0.3 of the Amazon Appstore SDK, and it looks like OneSignal-Android compiles against the latest available (3.0.4), so maybe that's where the issue is? That the function is not the same as the one in runtime?

**Comment by nan-li** [comment]
Hi everyone, thanks for your reports. 

We identified the bug in our native Android SDK's code and the fix will be included in the next release.

Thanks @vegaro for pointing out that the appstore v3.0.4 has a method name change. This wasn't the bug we needed to fix, but we used this information to make the SDK now compatible with v3.0.4.

**Comment by Klyado** [comment]
Hi @nan-li thanks for the good news (and @vegaro for taking a look at it).
When will the new version be released?

**Comment by nan-li** [comment]
Hi everyone, thanks for your patience.

We released the fix in the latest release of the OneSignal Flutter SDK, please see [version 5.0.3](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.0.3).

Please let us know if you have any remaining issues.

**Comment by tuantung** [comment]
Hi @nan-li 
Thanks for your update
I'm using 'onesignal_flutter: ^5.0.3' and got below log
Please help me check

> Fatal Exception: java.lang.RuntimeException
Unable to stop activity {xxxxxxxxxxx.MainActivity}: java.lang.NullPointerException: null cannot be cast to non-null type com.amazon.device.iap.PurchasingListener
Caused by java.lang.NullPointerException
null cannot be cast to non-null type com.amazon.device.iap.PurchasingListener
com.onesignal.core.internal.purchases.impl.TrackAmazonPurchase.onUnfocused (TrackAmazonPurchase.java:18)
com.onesignal.core.internal.application.impl.ApplicationService$handleLostFocus$1.invoke (ApplicationService.java:5)
com.onesignal.core.internal.application.impl.ApplicationService$handleLostFocus$1.invoke (ApplicationService.java:2)
com.onesignal.common.events.EventProducer.fire (EventProducer.java:21)
com.onesignal.core.internal.application.impl.ApplicationService.handleLostFocus (ApplicationService.java:22)
com.onesignal.core.internal.application.impl.ApplicationService.onActivityStopped (ApplicationService.java:71)
android.app.Application.dispatchActivityStopped (Application.java:495)
android.app.Activity.onStop (Activity.java:2686)
io.flutter.embedding.android.FlutterActivity.onStop (FlutterActivity.java)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1496)

**Comment by michael-joseph-payne** [comment]
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/1467850/12751b44-698a-4497-aec2-dd3f50cf4754)

Still present in 5.0.3

**Comment by nan-li** [comment]
Hi @michael-joseph-payne,

I cannot tell what the logs show. Is it a crash? Is it a "method not found" error? Is it an log from OneSignal or is it a log from Amazon Appstore SDK?

The crash users reported is `java.lang.IllegalArgumentException: Expected receiver of type com.amazon.device.iap.internal.d, but got kotlin.Unit` which has been fixed in 5.0.3.

**Comment by burakcbdn** [comment]
still gettiing this error on 5.0.4

**Comment by Vitor-Bukovitz** [comment]
@nan-li The issue still present on the version 5.0.3.
Is it fixed on 5.1.0? Can anyone confirm?
