### ISSUE TITLE
[Bug]: `optedIn` false after await for `optIn()`

### ISSUE THREAD

**Issue by enricobenedos** [OneSignal/OneSignal-Flutter-SDK#721]
### What happened?

We are trying to manage a flow in which we simply await for `optIn()` and the after we check if effectively `optedIn`.
 
`optedIn` is false after calling and awaiting `optIn()`, it becomes true after some time. So, what is the purpose to await the `optIn()` function?

### Steps to reproduce?

```Markdown
static Future<bool> enableNotifications() async {
    await OneSignal.User.pushSubscription.optIn();

    return OneSignal.User.pushSubscription.optedIn == true;
  }
```

### What did you expect to happen?

That simply after waiting for `optIn()` function the `optedIn` bool is `true`. It is the more natural behaviour.

It has no sense to await something that doesn't really finish as expected.

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Fixed in #735

**Comment by enricobenedos** [comment]
It doesn't fix the problem. I'm using `5.0.1` but nothing changed.

**Comment by petodavid** [comment]
It doesn't fix the problem. I'm using `5.0.3`

**Comment by chuanpham** [comment]
Hi @enricobenedos @petodavid, did you solve the problem?

**Comment by O-Nicks** [comment]
any suggestions ? still the same in 5.3.3
