### ISSUE TITLE
OneSignal.Notifications.addClickListener does not fire on push notification tap when app is killed (iOS)

### ISSUE THREAD

**Issue by ObserverMoment** [OneSignal/OneSignal-Flutter-SDK#723]
### How can we help?

Hi,

Firstly, should it fire when the app boots up when triggered by a push notification click? Or is this listener only triggered when app is open or in background?

If it is not possible to fire this on app load...

How is it possible to deeplink from a push notification into a Flutter app that is completely closed (not open and not in background)?

I am using this package to catch deeplinks as they arrive: https://pub.dev/packages/app_links.

Everything is working as expected when I open a link (either uni link or custom schema format) in all app states (open, background and killed). However, when I tap a push notification the initial link is only present when the app is open or in background, not when closed.

On android I don't seem to have this issue, only on iOS. I am wondering if there is some iOS specific issue with cold starts and push notifications? Or if there is some other way to capture the launch url on app boot that I am missing?

Thanks,

Rich

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gampixi** [comment]
Hi, I've also reported this issue via support. I was also having an issue with notification URLs not opening when the app is terminated. Yesterday I was told that they've been able to reproduce the issue on their end, so hopefully we can expect some sort of fix soon 👍

**Comment by ObserverMoment** [comment]
@gampixi , ok thanks, this is good news! Fingers crossed for a fix soon.

**Comment by MaximilianFlechtner** [comment]
Is there a workaround?

**Comment by cgmleadtech** [comment]
Is there any news regarding this?
Even by downgrading to 3.5 does not work

**Comment by alegos27** [comment]
We have the same problem: when app is closed the addClickListener callback is not fired on notification tap. After some tests we noticed that the first notification does not work if it is opened immediately or disappears shortly after. In case it disappears if you send a notification after the second works.

**Comment by alegos27** [comment]
Any news about it? We saw 5.0.2 version of iOS SDK but the Flutter SDK has no updates and the bug still remain.

**Comment by emawby** [comment]
Fixed in #752 and will be in the next release

**Comment by nan-li** [comment]
Hey all, since this was released in [v5.0.2 of this SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.0.2), I will close this issue. 
Please reach out if you are still experiencing any problems.

**Comment by burakcbdn** [comment]
Issue still exists on version 5.1.2, click listener triggers when app is on the background but not working when app is killed.

**Comment by jxr202** [comment]
我这边在使用 5.x.x 的时候，也碰到了该问题。Android 设备

**Comment by KristianLentino99** [comment]
Same here on iOS emulator. On android physical device it seems to work

**Comment by andy7076** [comment]
Issue still exists on version 5.2.0, click listener triggers when app is on the background but not working when app is killed.

UPDATE: Same issue exists on android,too.

**Comment by abdulmominsakib** [comment]
version 5.2.1, the issue still exists @nan-li

**Comment by rezwanahmedsami** [comment]
onesignal_flutter: ^5.1.2 in this version still same issue

**Comment by nandaprasesoft98** [comment]
in onesignal_flutter: ^5.2.2, still same issue
in original firebase, using FirebaseMessaging.onMessageOpenedApp.listen, if in background mode and clicking notification, the listener callback is called. But if in one signal (OneSignal.Notifications.addClickListener), the listener callback is not called

@OneSignal

**Comment by vdiaza** [comment]
I am experiecing same issue with version 5.2.3, anyone has found a solution?

**Comment by fimpact-nicole** [comment]
I'm experiencing same issue with version 5.2.5 and 5.2.6.

**Comment by midhun93** [comment]
I checked on the 5.2.6 but when the app is open from killed or coldstart stage the addClickListener() is not working. Any solution?

**Comment by midhuns1** [comment]
@nan-li When the app is open from the killed state the addclicklistener is not tiggering. Do you have any solution on this in flutter? I need to navigate to custom page when the notification is clicking based on the information from the additional data. 

I am stuck on this for releasing the important feature of build

**Comment by bahadirkalay** [comment]
Issue still exists on version 5.1.2, click listener triggers when app is on the background but not working when app is killed.

UPDATE: Same issue exists on android,too.

**Comment by stebaia** [comment]
Issue stille exist in 5.2.9!

**Comment by Gonzalo-Bruna** [comment]
I am experiencing the same issue right now. Any workarounds?

**Comment by Manuelkpatsu** [comment]
I'm currently experiencing the issue with the latest package where clicking on a notification to navigate to a screen ends up being fired more than once.

So once you are navigated to the screen, closing the screen does not work only once. You have to pop it several times before it gets closed. This is as a result of the multiple navigation that happens when you click on the notification.

It seems OneSignal.Notifications.addClickListener ends up firing the navigation several times.

Is anyone experiencing this issue and if there is a working solution, kindly help me with it.

**Comment by karroze** [comment]
This is absolutely insane that this CORE functionality has not been fixed for 2 years now. Is this some kind of joke? Especially considering that you charge 600 USD for mere 50k monthly users
